CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    ranking_points INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    player_a_id BIGINT NOT NULL,
    player_b_id BIGINT NOT NULL,
    best_of SMALLINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'WAITING_ACCEPT',
    winner_id BIGINT,
    FOREIGN KEY (player_a_id) REFERENCES users(id),
    FOREIGN KEY (player_b_id) REFERENCES users(id),
    FOREIGN KEY (winner_id) REFERENCES users(id),
    CHECK (status IN ('WAITING_ACCEPT', 'STARTED', 'FINISHED'))
);

CREATE TABLE IF NOT EXISTS games(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT NOT NULL,
    player_a_score SMALLINT DEFAULT 0,
    player_b_score SMALLINT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES matches(id)
);